#!/bin/bash

# generate-release-notes.sh
# Generates release notes based on git commits

OUTPUT_FILE=${1:-"release-notes.txt"}
SINCE_TAG=${2:-$(git describe --tags --abbrev=0 2>/dev/null || echo "")}

echo "📝 Generating Release Notes..."
echo "==========================================" > "$OUTPUT_FILE"
echo "RELEASE NOTES - $(date)" >> "$OUTPUT_FILE"
echo "==========================================" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"

if [ -z "$SINCE_TAG" ]; then
    echo "⚠️ No tags found. Generating notes for all commits."
    echo "## All Changes" >> "$OUTPUT_FILE"
    git log --pretty=format:"- %h %s (%an)" >> "$OUTPUT_FILE"
else
    echo "## Changes since $SINCE_TAG" >> "$OUTPUT_FILE"
    git log "${SINCE_TAG}..HEAD" --pretty=format:"- %h %s (%an)" >> "$OUTPUT_FILE"
fi

echo "" >> "$OUTPUT_FILE"
echo "==========================================" >> "$OUTPUT_FILE"
echo "Generated by Jenkins Pipeline" >> "$OUTPUT_FILE"

echo "✅ Release notes generated at $OUTPUT_FILE"
